"""initial_schema

Revision ID: 8e2b53f6212f
Revises: 
Create Date: 2026-06-09 22:08:38.978736

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '8e2b53f6212f'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('exams',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=500), nullable=False),
    sa.Column('institution_name', sa.String(length=500), nullable=False),
    sa.Column('teacher_name', sa.String(length=255), nullable=False),
    sa.Column('exam_date', sa.Date(), nullable=False),
    sa.Column('instructions', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_exams_id'), 'exams', ['id'], unique=False)
    op.create_table('topics',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_topics_id'), 'topics', ['id'], unique=False)
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('full_name', sa.String(length=255), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('hashed_password', sa.String(length=255), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.create_index(op.f('ix_users_id'), 'users', ['id'], unique=False)
    op.create_table('exam_configs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('exam_id', sa.Integer(), nullable=False),
    sa.Column('total_questions', sa.Integer(), nullable=False),
    sa.Column('total_topics', sa.Integer(), nullable=False),
    sa.Column('questions_per_topic', sa.Integer(), nullable=False),
    sa.Column('version_count', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['exam_id'], ['exams.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('exam_id')
    )
    op.create_index(op.f('ix_exam_configs_id'), 'exam_configs', ['id'], unique=False)
    op.create_table('exam_topics',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('exam_id', sa.Integer(), nullable=False),
    sa.Column('topic_id', sa.Integer(), nullable=False),
    sa.Column('questions_count', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['exam_id'], ['exams.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['topic_id'], ['topics.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_exam_topics_exam_id'), 'exam_topics', ['exam_id'], unique=False)
    op.create_index(op.f('ix_exam_topics_id'), 'exam_topics', ['id'], unique=False)
    op.create_index(op.f('ix_exam_topics_topic_id'), 'exam_topics', ['topic_id'], unique=False)
    op.create_table('exam_versions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('exam_id', sa.Integer(), nullable=False),
    sa.Column('version_code', sa.String(length=10), nullable=False),
    sa.Column('pdf_path', sa.String(length=500), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['exam_id'], ['exams.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_exam_versions_exam_id'), 'exam_versions', ['exam_id'], unique=False)
    op.create_index(op.f('ix_exam_versions_id'), 'exam_versions', ['id'], unique=False)
    op.create_table('questions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('topic_id', sa.Integer(), nullable=False),
    sa.Column('statement_text', sa.Text(), nullable=True),
    sa.Column('statement_latex', sa.Text(), nullable=True),
    sa.Column('image_path', sa.String(length=500), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['topic_id'], ['topics.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_questions_id'), 'questions', ['id'], unique=False)
    op.create_index(op.f('ix_questions_topic_id'), 'questions', ['topic_id'], unique=False)
    op.create_table('alternatives',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('question_id', sa.Integer(), nullable=False),
    sa.Column('content_text', sa.Text(), nullable=True),
    sa.Column('content_latex', sa.Text(), nullable=True),
    sa.Column('image_path', sa.String(length=500), nullable=True),
    sa.Column('is_correct', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['question_id'], ['questions.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_alternatives_id'), 'alternatives', ['id'], unique=False)
    op.create_index(op.f('ix_alternatives_question_id'), 'alternatives', ['question_id'], unique=False)
    op.create_table('exam_version_questions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('exam_version_id', sa.Integer(), nullable=False),
    sa.Column('question_id', sa.Integer(), nullable=False),
    sa.Column('order_number', sa.Integer(), nullable=False),
    sa.Column('topic_order', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['exam_version_id'], ['exam_versions.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['question_id'], ['questions.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_exam_version_questions_exam_version_id'), 'exam_version_questions', ['exam_version_id'], unique=False)
    op.create_index(op.f('ix_exam_version_questions_id'), 'exam_version_questions', ['id'], unique=False)
    op.create_table('exam_version_alternatives',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('exam_version_question_id', sa.Integer(), nullable=False),
    sa.Column('alternative_id', sa.Integer(), nullable=False),
    sa.Column('letter', sa.String(length=1), nullable=False),
    sa.Column('order_number', sa.Integer(), nullable=False),
    sa.Column('is_correct_snapshot', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['alternative_id'], ['alternatives.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['exam_version_question_id'], ['exam_version_questions.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_exam_version_alternatives_exam_version_question_id'), 'exam_version_alternatives', ['exam_version_question_id'], unique=False)
    op.create_index(op.f('ix_exam_version_alternatives_id'), 'exam_version_alternatives', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_exam_version_alternatives_id'), table_name='exam_version_alternatives')
    op.drop_index(op.f('ix_exam_version_alternatives_exam_version_question_id'), table_name='exam_version_alternatives')
    op.drop_table('exam_version_alternatives')
    op.drop_index(op.f('ix_exam_version_questions_id'), table_name='exam_version_questions')
    op.drop_index(op.f('ix_exam_version_questions_exam_version_id'), table_name='exam_version_questions')
    op.drop_table('exam_version_questions')
    op.drop_index(op.f('ix_alternatives_question_id'), table_name='alternatives')
    op.drop_index(op.f('ix_alternatives_id'), table_name='alternatives')
    op.drop_table('alternatives')
    op.drop_index(op.f('ix_questions_topic_id'), table_name='questions')
    op.drop_index(op.f('ix_questions_id'), table_name='questions')
    op.drop_table('questions')
    op.drop_index(op.f('ix_exam_versions_id'), table_name='exam_versions')
    op.drop_index(op.f('ix_exam_versions_exam_id'), table_name='exam_versions')
    op.drop_table('exam_versions')
    op.drop_index(op.f('ix_exam_topics_topic_id'), table_name='exam_topics')
    op.drop_index(op.f('ix_exam_topics_id'), table_name='exam_topics')
    op.drop_index(op.f('ix_exam_topics_exam_id'), table_name='exam_topics')
    op.drop_table('exam_topics')
    op.drop_index(op.f('ix_exam_configs_id'), table_name='exam_configs')
    op.drop_table('exam_configs')
    op.drop_index(op.f('ix_users_id'), table_name='users')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_table('users')
    op.drop_index(op.f('ix_topics_id'), table_name='topics')
    op.drop_table('topics')
    op.drop_index(op.f('ix_exams_id'), table_name='exams')
    op.drop_table('exams')
    # ### end Alembic commands ###
